### PR TITLE
Support for PHP 8

### PR DESCRIPTION
**Pull request by Lukeboy25**

### CODE REVIEW

**Comment by AlexLisenkov** [comment]
Released in version 3.0.0

**Comment by Lukeboy25** [comment]
Thanks @AlexLisenkov

**Comment by CreateBerend** [comment]
Thanks @AlexLisenkov

**Comment by Krilo89** [comment]
Hi,
It's fine to 'support' PHP 8, but why remove PHP 7? The package itself will run on PHP 7, so why remove this version?

Just like https://github.com/andreas-glaser/doctrine-rql you can support multiple PHP versions (^7.4 and ^8.0). This module is literally a bridge for: andreas-glaser/doctrine-rql and paknahad/jsonapi-bundle which both have support for PHP 7.4, so this 'new version' does not make sense to me.

I added a new PR: https://github.com/mnugter/jsonapi-rql-finder-bundle/pull/7. The code will still work, but more people can use this in combination with doctrine-rql and jsonapi-bundle. Tag it as 3.01 or 2.0.1.

**Pull request merged**
