### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by AlexLisenkov**
Upgrade depencencies and added some fancy badges.

https://github.com/paknahad/jsonapi-bundle/releases/tag/v3.0.0
https://github.com/andreas-glaser/doctrine-rql/releases/tag/0.3.0

I suggest to create a new tag with mayor version update.

### CODE REVIEW

**Comment by AlexLisenkov** [comment]
Are you planning on merging this?

**Comment by paknahad** [comment]
Hi @mnugter

Could you please merge this PR?

**Comment by AlexLisenkov** [comment]
Mnugter granted me access to maintain this repo. I could merge but before I do I have

**Comment by AlexLisenkov** [comment]
Mnugter granted me access to maintain this repo. I could merge but before I do I have a question about versioning.

This repository does not have any releases and we recently tagged a new version for symfony 5 in the jsonapi-bundle. Of course this repository has a big dependency on your bundle and should be synchronized someway. What are your ideas on this?

**Comment by paknahad** [comment]
in my opinion, you can tag the current code by V1.0, after that merge this PR

feel free to tag this repo in any way you want :)

**Comment by AlexLisenkov** [comment]
I'm currently working on this.

Version 1 will be for jsonapi-bundle below version 3.
Version 2 will be for jsonapi-bundle ^3 (symfony 4)
Version 3 will be for jsonapi-bundle ^4 (symfony 5)

Will release version 2 first and will be working on version 3 in a later stage.

**Pull request merged**
